### ISSUE TITLE
Possible corrupted rows in weather dataset

### ISSUE THREAD

**Issue by jaberkow** [yandex-research/shifts#18]
There are four columns in the weather dataset that, at first glance, would seem to be boolean indicators for the availability of other features: `cmc_avaliable`, `gfs_available`, `wrf_available`, and `gfs_soil_temperature_available`.  However, there are two rows where each of these features are equal to a value _between_ 0 and 1.  Furthermore, these two rows appear to correspond to the same time, latitude, and longitude and have an anomalous value for `gfs_soil_temperature` (large and negative, but not -9999 as is the case for when `gfs_soil_temperature_available==0`).  Should we interpret these two data points as corrupted/discard them?

**Comment by VatsalRaina** [comment]
@jaberkow Hi - good spot! The weather dataset intentionally has had 2 dummy rows inserted (the two that you have identified) into the training set. These dummy rows were generated by averaging all the previous samples. Why? Because the weather dataset has been constructed for 2 tasks: 1) a regression-based task where the aim is to predict the temperature (this is the task that the shifts challenge weather track is based upon) 2) a classification-based task with the aim to predict the precipitation class. The second task has not been discussed yet in the arxiv paper. As the evaluation sets have a distributional shift with regard to the training set, all precipitation classes are not present in the training set. Therefore, dummy rows are added per missing precipitation class in order to be able to train classification models with the correct number of output classes. In summary, you can ignore (if you want) the dummy rows for the purpose of the regression-based task in the shifts challenge.
